### ISSUE TITLE
Everything gives protein, including plain bread

### ISSUE THREAD

**Issue by DragonFeyAni** [dannydjdk/Nutritional-Balance#33] opened 2023-09-23 00:29 UTC
I keep getting "engorged" because everything seems to have a secret protein value even though the food item shouldn't have protein and/or doesn't list protein. Even the vanilla food items like bread increase the protein value but I'm also seeing this on many Pam's food items like toast that should have zero protein value to it. Strangely enough, the vanilla bread also lists itself as being "fruits, carbs" so idk if there's just something weird/wrong on my side or what but it's been very frustrating trying to keep nutrition balanced with various food items when everything keeps unintentionally adding to my protein bar and resulting in a debuff.

**Comment by dannydjdk** [comment] 2023-09-23 14:17
Thanks for the report! I've never seen anything quite like. Can you provide some details to help me reproduce the problem on my side?
What version of Nutritional Balance are you using?
Are you using a modpack? Is so, please give me a link to the modpack.
If not, can you give me a list of the mods you are using and the forge version? Or even better, if you are using a mod loader, like Curseforge, please export the pack and post it here for me.

**Comment by PINPAL** [comment] 2023-09-23 17:32
I'm also getting this but just for the vanilla bread.
It doesn't have a protein tag but still gives protein (in fact it has no food tags).

Nutritional Balance 1.19.2-4.2.0

**UPDATE**
This issue occurs ONLY when I have FarmersDelight installed alongside Nutritional Balance.

Just with Nutrional Balance:
`Nutritional Balance 1.19.2-4.2.0`
![image](https://github.com/dannydjdk/Nutritional-Balance/assets/18197217/cf3d7fff-6692-473e-b360-5702c2822e02)

With Farmers Delight
`Nutritional Balance 1.19.2-4.2.0`
`Farmer's Delight 1.19.2-1.2.3`
![image](https://github.com/dannydjdk/Nutritional-Balance/assets/18197217/6d9b2b16-9153-436c-adc8-ab650fc2be50)

**Comment by dannydjdk** [comment] 2023-09-23 20:22
By default, bread is explicitly tagged with carbs which should prevent it from traversing recipes. So, either a custom data pack is involved, or another mod has tagged bread as protein. Are you able to install a mod that shows item tags?

This seems different than what @DragonFeyAni was reporting.
> the food item shouldn't have protein and/or doesn't list protein

This seems to suggest that the tooltip is not showing protein but is still providing protein. If that's the case, there's a much bigger issue at play.

**Comment by PINPAL** [comment] 2023-09-23 21:08
> By default, bread is explicitly tagged with carbs which should prevent it from traversing recipes. So, either a custom data pack is involved, or another mod has tagged bread as protein. Are you able to install a mod that shows item tags?
> 
> This seems different than what @DragonFeyAni was reporting.
> 
> > the food item shouldn't have protein and/or doesn't list protein
> 
> This seems to suggest that the tooltip is not showing protein but is still providing protein. If that's the case, there's a much bigger issue at play.

Apple with Farmers Delight
![image](https://github.com/dannydjdk/Nutritional-Balance/assets/18197217/77ca9406-b713-4cff-b60c-b2bfa18006cc)
Apple WITHOUT Farmers Delight
![image](https://github.com/dannydjdk/Nutritional-Balance/assets/18197217/e0f7253b-e5dd-4772-9515-8899c55a85b1)


Bread with Farmers Delight:
![image](https://github.com/dannydjdk/Nutritional-Balance/assets/18197217/6b311421-0b8c-4ebc-b98b-7f8cfc664c8c)
Bread WITHOUT Farmers Delight (no tags):
![image](https://github.com/dannydjdk/Nutritional-Balance/assets/18197217/fa9c2874-1a92-4add-8c28-48baa8bb306c)

**Comment by PINPAL** [comment] 2023-09-23 21:16
Additional Notes:
By adding the tag
`forge:nutrients/carbs` manually using a datapack or KubeJS, it forces the bread to NOT have any protein only carbs.

**Comment by dannydjdk** [comment] 2023-09-24 01:55
Thanks for the details @PINPAL. No idea how, but it looks like specifically 1.19.2-4.2.0 did not have bread in the forge:nutrients/carbs. I'll have an update to fix this soon. This should also affect anything crafted with bread that is getting it's nutrients from bread.

**Comment by dannydjdk** [comment] 2023-09-24 02:13
Just uploaded fixed version 1.19.2-4.2.1. It is awaiting Curseforge review and should be available soon.

The 1.20.* versions already have this tag, so they should be fine, but the 1.18.2-3.20 does not. So, that fix will be coming as well.

**Comment by VincentFoulon80** [comment] 2023-11-05 11:34
I encountered a similar issue today with NB 5.1.0 on MC 1.20.1.
Most of the food (if not all) seemed to give protein in some way.
For example, Farmer's Delight Vegetable soup is intended to give veggies & carbs, but when eaten the carbs meter does not increase but the protein one seems to have increased instead.
![image](https://github.com/dannydjdk/Nutritional-Balance/assets/26797476/b31a5df1-6e65-48e6-ab8b-92d754d887fd)

Restarting the server has fixed that issue. 

By the way (may be its own issue), at each restart I noticed the nutrients of most foods tend to change randomly. My first guess is that some recipes accepts veggies or fruits, and when starting the server it assign nutrients based on recipes but by picking random recipes. Most of the time Ratatouille provides only veggies, but rarely it also provides fruits. When he does this I just restart the server and it fixes itself. 
Also the nutrients on the nutrients screen seem to have a random order each time I restart (currently it is Carbs Fruits Sugar Protein Veggies).

**Comment by dannydjdk** [comment] 2023-11-05 16:00
Thanks for the details @VincentFoulon80. This is probably a desync issue.

There seems to be a randomness to the order that Minecraft loads item tags and recipes. What may be happening is that the server and client are sometimes loading the  recipes in different orders. Since Nutritional Balance stops traversing through recipes once it finds nutrients, the server and client might be getting them from different recipes. This also explains the difference in the display order which, by itself, shouldn't really be a problem.

So, what I probably need to do is sort the tags and recipes before traversing them.

Of course, the end goal is for the automatic tagging based on recipes to work reliably, but in the meantime, a workaround is to explicitly tag the foods that are causing problems.

**Comment by VincentFoulon80** [comment] 2023-11-05 16:45
Maybe as a way to decide which nutrient to give to a given recipe is to load all the possible recipes for a given food item and do a count of the appearance of a given nutrient in each variant, and eliminate those that appear occasionally.

Another way "best case" (but heaviest amount of work) I can think of is to override recipes that have variations to propose different nutrients for the same food based on the recipe the user used.
For example, the Ratatouille recipe accepts any vegetables (Veggies) as well as potatoes (Veggies, Carbs). Nutritional Balance would make two Ratatouille variants, one with only Veggies and the other with Veggies, Carbs. that would add more unstackable items but also get rid of recipe clash and let the user chose the recipe based on their needs.

**Comment by dannydjdk** [comment] 2023-11-05 22:04
I had considered an option similar to your first suggestion, except that I would have had it just grab all nutrients from all recipes. But, I felt this would increase the likelihood of a really simple food providing a bunch of nutrients. Plus, I would have to account for infinite loops in recipes trees.

The second suggestion is likely impossible. Even if I could figure out a way to do it, the potential that it would break other mods would be very high. 

What I've done (for release with the next version) is to explicitly sort the tags and recipes before working with them. The result should be that you always get the same nutrients in the same order. If they turn out to be not what you want, you can add tags for the item. If they are what you want, you don't have to worry about them changing on server reboot. Though, adding and removing mods could change them.

Also, the client is now relying on the server to provide nutrient stats rather than simultaneously calculating it with (what is supposed to be) the same data. This way, if something weird does happen server side (like bread providing protein), the tooltip will show that. So, the possibility of the food providing something different than what the tooltip shows should be eliminated. This should fix the issue reported by the OP.

**Comment by dannydjdk** [comment] 2023-11-07 01:31
The fix has been released in the latest version for 1.18.2, 1.19.2, and 1.20.*.

**Closed as completed by dannydjdk** 2023-11-07 01:31 UTC
