### ISSUE TITLE
Fail connecting to dedicated server (1.19.2)

### ISSUE THREAD

**Issue by lebanni** [dannydjdk/Nutritional-Balance#23] opened 2022-11-03 06:23 UTC
Minecraft v1.19.2
forge-1.19.2-43.1.47
nutritionalbalance-1.19.1-4.1.1.jar

Client failed to connect to server : https://imgur.com/a/3pgirZC

debug.log : https://gist.github.com/lebanni/781fdbfe863ead4f22bc29ed6d421b91

**Comment by lebanni** [comment] 2022-11-03 06:35
Same with only nutritional balance : https://imgur.com/a/1Z12X5s

**Comment by dannydjdk** [comment] 2022-11-03 14:53
Thanks for the report. This is a known issue mentioned in the change log for this version and is the reason it's still in alpha. However, there was not an issue for it, so I'll use this issue to track progress moving forward.

Unfortunately, something changed in Minecraft or Forge's SaveData or networking classes that hasn't been clearly documented. The good news is that I can consistently repeat the problem in my dev environment. The bad news is that I haven't been able to nail down the problem yet. Nothing about the problem is being logged anywhere. Client/Server issues are practically impossible to debug while maintaining a connection. So, troubleshooting has been a time consuming process of elimination.

**Comment by dannydjdk** [comment] 2022-11-05 19:36
Problem only occurs for op users. Therefore it is likely related to commands, and a fix will likely be coming soon.

Deop as a temporary workaround.

**Comment by dannydjdk** [comment] 2022-11-06 17:05
Fixed in version 1.19.2-4.1.3

**Closed as completed by dannydjdk** 2022-11-06 17:05 UTC
Labels: bug
